# Configurazione dei logger e degli handler in Java tramite logging.properties

# Definisce quali handler utilizzare globalmente.
# In questo caso, i log saranno gestiti sia dalla console che da un file.
handlers= java.util.logging.ConsoleHandler, java.util.logging.FileHandler

# Imposta il livello globale per tutti i logger e gli handler.
# Solo i messaggi con livello INFO o superiore (INFO, WARNING, SEVERE) verranno registrati.
.level= INFO

# Proprietà specifiche del FileHandler
# pattern: nome e percorso del file di log, %u aggiunge un numero unico se più istanze creano lo stesso file
java.util.logging.FileHandler.pattern = C:/Users/Administrator/Desktop/progetti/Esercizi-Java/Settimana5 esercizio sui log/logs/carvedrockfitness%u.log
# limit: dimensione massima del file di log in byte (qui 5000 byte)
java.util.logging.FileHandler.limit = 5000
# count: numero massimo di file di log da mantenere (rotazione dei log)
java.util.logging.FileHandler.count = 1
# formatter: definisce il formato dei log su file (XML in questo caso)
java.util.logging.FileHandler.formatter = java.util.logging.XMLFormatter

# Proprietà specifiche del ConsoleHandler
# livello dei log in console (OFF significa che non vengono mostrati messaggi in console)
java.util.logging.ConsoleHandler.level = OFF
# formatter: definisce il formato dei log mostrati in console (SimpleFormatter in questo caso)
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter