# Definizione delle reti Docker che i container useranno per comunicare tra loro
networks:
  default:   # rete di default creata da docker-compose per collegare i servizi

# Sezione che definisce i vari servizi (container) dell'applicazione
services:

  # Servizio del database
  db:
    image: mysql:8.0   # immagine Docker ufficiale di MySQL versione 8.0 da Docker Hub

    container_name: library   # nome personalizzato assegnato al container

    ports:
      - 3306:3306   # mappa la porta 3306 del computer (host) alla porta 3306 del container
      # permette di connettersi al database dal computer locale

    volumes:
      - "./.data/db:/var/lib/mysql"
      # collega una cartella locale (.data/db) alla cartella del container dove MySQL salva i dati
      # serve per mantenere i dati anche se il container viene eliminato (persistenza)

    environment:
      MYSQL_ROOT_PASSWORD: pass
      # imposta la password dell'utente root di MySQL

      MYSQL_DATABASE: library_db
      # dovrebbe creare automaticamente un database chiamato "library_db"