server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/esempio
    username: esempio
    password: esempio
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  sql:
    init:
      mode: always